agent_class: 'agents.adaptive_ftrl.AdaptiveFTRL'

init_kwargs:
  lr_constant: 1
  lr_pow_X: 0.0
  lr_pow_A: 0.0
  lr_pow_H: 0.0
  lr_pow_T: 0.0
  lr_pow: -0.5

  ix_constant: 0.05
  ix_pow_X: 0.0
  ix_pow_A: 0.0
  ix_pow_H: 0.0
  ix_pow_T: 0.0
  ix_pow: -0.5
  
  name: 'Tweaked AdaptiveFTRL'
